# Generated by Django 3.1.12 on 2025-07-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Hoodie', 'Hoodie'), ('Jacket', 'Jacket'), ('Dress', 'Dress'), ('Skirt', 'Skirt'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing_items/')),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
    ]
